### ISSUE TITLE
i18n init throws "TypeError: this.firestore.collection is not a function" when using firebase v9+

### ISSUE THREAD

**Issue by karel-suchomel-ed** [gregfenton/i18next-node-firestore-backend#1]
I wanted to implement this package with the newest version of firebase, but can't figure out any workaround for this error.

it throws this error when I specify the firestore field in backend init:

`[TypeError: this.firestore.collection is not a function. (In 'this.firestore.collection(this.opts.collectionName)', 'this.firestore.collection' is undefined)]`

I am positive, that I have correctly set up the firestore, the loadTranslationsToFirestore function is working on its own, but I cannot get the translations from the backend.
This is my whole init function:

`i18n
    .use(Backend)
    .use(initReactI18next)
    .use(languageDetectorPlugin)
    .init({
      backend: {
        firestore: getFirestore(firebase),
        collectionName: REACT_APP_I18N_FIRESTORE_COLLECTION_NAME,
        languageFieldName: REACT_APP_I18N_LANGUAGE_FIELD_NAME,
        namespaceFieldName: REACT_APP_I18N_NAMESPACE_FIELD_NAME,
        dataFieldName: REACT_APP_I18N_DATA_FIELD_NAME,
        debug: true,
      },
      fallbackLng: LOCALE_CZ,
      load: 'currentOnly',
      ns: LIST_OF_NAMESPACES,
      react: {
        useSuspense: false,
      },
});`

As you can see, everything is the same but the field firestore. You are using version 8, which gets the firestore with firebase.firestore() and gets its collections with firebase.firestore().collection() which is no longer supported in v9.

Is there a way, I can use this package with firebase v9+?

**Comment by gregfenton** [comment]
Because of the modular nature of v9, it looks like I'd need to have a different approach for getting access to the capabilities of the SDK.  This likely means an entirely different file/branch or possibly even a separate repository.

We'll need to either ask the caller to provide each of the API calls, or we need to actually import Firestore APIs directly.  With the v8 library, all we need is the `firebase` object and we have access to everything we need.  With v9, we'd need at least  `firestore`, `collection`, `where`, and `getDocs`.

Thoughts?

**Comment by karel-suchomel-ed** [comment]
Hi, I have managed to overwrite your index.js file locally, to work with the firebase v9 and TypeScript. In my opinion, including the Firebase as package dependency is not the way, as someone may use Firebase web SDK in their project and someone may use @react-native-firebase. 
I would go with a separate file, made for the v9 version of Firestore and request the user to provide all the necessary functions. All I needed to add was `firestore` instance, `collection`, `query`, `where` and `getDocs`.

**Comment by karel-suchomel-ed** [comment]
This is the snippet of my getLanguageAndNamespace function:
```
async getLanguageAndNamespace (lang, ns) {

    if (
      !this.firestore ||
      !this.opts.collectionName ||
      !this.opts.languageFieldName ||
      !this.opts.namespaceFieldName
    ) {
      return null;
    }

    const localizationRef = collection(
      this.firestore,
      this.opts.collectionName,
    );

    const q = query(
      localizationRef,
      where(this.opts.languageFieldName, '==', lang),
      where(this.opts.namespaceFieldName, '==', ns ? ns : 'general'),
    );

    const querySnapshot = await getDocs(q);

    if (querySnapshot.empty) {
      return null;
    }

    return querySnapshot.docs[0].data();
}
```

**Comment by gregfenton** [comment]
Feel free to push this change as a PR.

I agree with not making Firebase a dependency of the NPM.  I am using this with `react-native-firebase` myself.  The problem we're facing right now is that RNF still uses the "v8 API  syntax" whereas Firebase Web SDK is now onto the "v9 API syntax"....this will make supporting both in a single codebase difficult.

I likely will split the repo to have separate v8 and v9 support.

**Comment by Dildar-Khan** [comment]
Hello @gregfenton any news on solving this issue?

**Comment by gregfenton** [comment]
I have not yet, unfortunately.  I have been busy with other priorities.

Still happy to receive a PR  😄
